spring.application.name=aula-sd
# URL de conexão com o PostgreSQL (substitua 'postgres' pelo seu banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/aula-sd

# Credenciais de acesso
spring.datasource.username=postgres
spring.datasource.password=Jose2608

# Driver do PostgreSQL (opcional nas versões mais recentes, mas recomendado)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
