-- 07_explain.sql
-- Arquivo de documentação da análise de desempenho.
-- O validador SQL usado no projeto não reconhece o comando EXPLAIN.
-- Os comandos executáveis estão em 07_explain_postgresql.sql.
-- Eles devem ser executados em uma conexão PostgreSQL.
--
-- Consulta 1: JOIN entre consulta, paciente e médico.
-- EXPLAIN ANALYZE SELECT c.id_consulta, p.nome AS paciente, m.nome AS medico, c.data_consulta
-- FROM consulta c JOIN paciente p ON p.cpf = c.cpf_paciente
-- JOIN medico m ON m.crm = c.crm_medico
-- WHERE c.crm_medico = 'CRM-MA-00001' ORDER BY c.data_consulta;
--
-- Consulta 2: busca de exames por paciente.
-- EXPLAIN ANALYZE SELECT e.id_exame, e.tipo, e.status, e.data_envio
-- FROM exame e JOIN paciente p ON p.cpf = e.cpf_paciente
-- WHERE e.cpf_paciente = '11111111101' ORDER BY e.data_envio DESC;
--
-- Consulta 3: agregação de pagamentos.
-- EXPLAIN ANALYZE SELECT forma_pagamento, COUNT(*) AS quantidade, SUM(valor) AS total
-- FROM pagamento WHERE data_pagamento >= DATE '2025-01-01' GROUP BY forma_pagamento;
